- name: Run data update script
  env:
    RTE_CLIENT_ID: ${{ secrets.RTE_CLIENT_ID }}
    RTE_CLIENT_SECRET: ${{ secrets.RTE_CLIENT_SECRET }}
    MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
  run: python rte_extract_and_load.py
