name: Hourly Data Update

on:
  schedule:
    - cron: '0 * * * *'  #run hourly
  workflow_dispatch:  #allows manual trigger from GitHub UI

jobs:
  update-database:
    runs-on: ubuntu-latest

    permissions:
      contents: write #needed to push changes back

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run data update script
        env:
          RTE_CLIENT_ID: ${{ secrets.RTE_CLIENT_ID }}
          RTE_CLIENT_SECRET: ${{ secrets.RTE_CLIENT_SECRET }}
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: python rte_wholesale_EL.py
